# Environment Canada's database site ID
siteid = "6016527"
#siteid = '6016527' #ottawa 
#siteid = '8300060' #pei
#siteid = "7016294" #error prone site

# download fresh daily data of this siteID 
scrapedailies = true
scrapenormals = true

# 1: pull province's list of files, search for matches to siteID
# 2: generate list of paths using siteID (faster, recommended)
scrapemethod = 2

# for scrapemethod 1, amount of time the get is allowed to run for
timeout = 360

# range of years to consider for scrarping daily data (inclusive)
# use the format "[yyyy, YYYY]"
years = "[1981, 2010]"

# amount of missing data across year range in % that will cause an error
errorthreshold = 10

# print messages
verbose = true

# Temperature plot of all daily data
rplot = false